kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 
        from_secret: ssh_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      script:
        - sudo -i
        - cd /root/xuan/portfolio
        - git pull
        - npm install
        - npm run build
        - npm install --production
        - pm2 restart "next-app" || pm2 start npm --name "next-app" -- start

trigger:
  branch:
    - main
  event:
    - push